---
title: "Table 11.1/11.2 HERS data"
format: html
vignette: >
  %\VignetteIndexEntry{Table 11.1/11.2 HERS data}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
execute:
  warning: false
  message: false
---

```{r}
#| include: false
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
library(rmb)
```

This vignette implements an expanded, dataset-organized RMB2e analysis workflow for `hers_nodm_visit4_only`.

## Study design

```{r study-design}
data(rmb_datasets, package = "rmb")
rmb_datasets$study_design[rmb_datasets$object == "hers_nodm_visit4_only"]
```


```{r load-hers_nodm_visit4_only}
data(hers_nodm_visit4_only, package = "rmb")
dat <- hers_nodm_visit4_only
dim(dat)
head(dat)
summary(dat)
```

## Variable labels

```{r labels}
var_labels <- vapply(dat, function(x) {
  lbl <- attr(x, "label")
  if (is.null(lbl) || length(lbl) == 0 || all(lbl == "")) NA_character_ else paste(as.character(lbl), collapse = "; ")
}, character(1))
stats::setNames(var_labels, names(dat))
```

## RMB2e analysis families

```{r analyses, results='asis'}
helper_path <- "analysis_helpers.r"
if (!file.exists(helper_path)) {
  helper_path <- file.path("vignettes", "analysis_helpers.r")
}
source(helper_path)
run_rmb_dataset_analyses(dat, "hers_nodm_visit4_only")
```

## Source

- UCSF Regression Methods companion data: https://regression.ucsf.edu/sites/g/files/tkssra16191/files/wysiwyg/home/data/hers_nodm_visit4_only.dta
- Book: Vittinghoff E, Glidden DV, Shiboski SC, McCulloch CE (2012). *Regression Methods in Biostatistics* (2nd edition).
